//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaxEntities : DbContext
    {
        public CinemaxEntities()
            : base("name=CinemaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DalAspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<DalAspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<DalAspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<DalAspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<DalCine> Cine { get; set; }
        public virtual DbSet<DalCuenta> Cuenta { get; set; }
        public virtual DbSet<DalDetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<DalEmpleado> Empleado { get; set; }
        public virtual DbSet<DalFuncion> Funcion { get; set; }
        public virtual DbSet<DalMembresia> Membresia { get; set; }
        public virtual DbSet<DalPelicula> Pelicula { get; set; }
        public virtual DbSet<DalSala> Sala { get; set; }
        public virtual DbSet<DalTelCin> TelCin { get; set; }
        public virtual DbSet<DalTelEmp> TelEmp { get; set; }
        public virtual DbSet<DalVenta> Venta { get; set; }
    }
}
