//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DalDetalleVenta
    {
        public long clave_venta { get; set; }
        public decimal subtotal { get; set; }
        public string asiento { get; set; }
        public string tipo_asiento { get; set; }
    
        public virtual DalVenta Venta { get; set; }
    }
}
