//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DalFuncion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DalFuncion()
        {
            this.Venta = new HashSet<DalVenta>();
        }
    
        public long clave_fun { get; set; }
        public long clave_pel { get; set; }
        public long clave_sal { get; set; }
        public System.DateTime hora_ini { get; set; }
        public System.DateTime hora_fin { get; set; }
        public System.DateTime fecha { get; set; }
        public int cupo { get; set; }
    
        public virtual DalPelicula Pelicula { get; set; }
        public virtual DalSala Sala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DalVenta> Venta { get; set; }
    }
}
