//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DalVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DalVenta()
        {
            this.DetalleVenta = new HashSet<DalDetalleVenta>();
        }
    
        public long clave_venta { get; set; }
        public long clave_mem { get; set; }
        public long clave_fun { get; set; }
        public long clave_emp { get; set; }
        public decimal total { get; set; }
    
        public virtual DalCuenta Cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DalDetalleVenta> DetalleVenta { get; set; }
        public virtual DalEmpleado Empleado { get; set; }
        public virtual DalFuncion Funcion { get; set; }
        public virtual DalMembresia Membresia { get; set; }
    }
}
