/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Toolkit;
import controlador.*;
import java.awt.Color;
import java.sql.Date;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author MILAN
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        setIcon();
    }

    /**
     * This method sets the application icon
     */
    private void setIcon() {
        super.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagenes/logo_oscuro.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpPrincipal = new javax.swing.JTabbedPane();
        panelAdministracion = new javax.swing.JPanel();
        tpAdministración = new javax.swing.JTabbedPane();
        panelEmpleado = new javax.swing.JPanel();
        panelInfoEmp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        etNombreEmp = new javax.swing.JLabel();
        etAppEmp = new javax.swing.JLabel();
        etApmEmp = new javax.swing.JLabel();
        etFechaEmp = new javax.swing.JLabel();
        etContEmp = new javax.swing.JLabel();
        ctNombreEmp = new javax.swing.JTextField();
        ctAppEmp = new javax.swing.JTextField();
        ctApmEmp = new javax.swing.JTextField();
        ctFechaEmp = new javax.swing.JTextField();
        ctContEmp = new javax.swing.JTextField();
        etFechaEmp1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        etColoniaEmp = new javax.swing.JLabel();
        etNumeroEmp = new javax.swing.JLabel();
        etCalleEmp = new javax.swing.JLabel();
        ctColoniaEmp = new javax.swing.JTextField();
        ctCalleEmp = new javax.swing.JTextField();
        ctNumeroEmp = new javax.swing.JTextField();
        btAgregaEmp = new javax.swing.JButton();
        btEliminaEmp = new javax.swing.JButton();
        btActualizaEmp = new javax.swing.JButton();
        btCancelaEmp = new javax.swing.JButton();
        etMensajeEmp = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        panelMembresia = new javax.swing.JPanel();
        panelInfoEmp2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        etNombreMem = new javax.swing.JLabel();
        etAppMem = new javax.swing.JLabel();
        etApmMem = new javax.swing.JLabel();
        etFechaMem = new javax.swing.JLabel();
        ctNombreMem = new javax.swing.JTextField();
        ctAppMem = new javax.swing.JTextField();
        ctApmMem = new javax.swing.JTextField();
        etFechaEmp2 = new javax.swing.JLabel();
        ctFechaMem = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        etColoniaMem = new javax.swing.JLabel();
        etNumeroMem = new javax.swing.JLabel();
        etCalleMem = new javax.swing.JLabel();
        ctColoniaMem = new javax.swing.JTextField();
        ctCalleMem = new javax.swing.JTextField();
        ctNumeroMem = new javax.swing.JTextField();
        btAgregaMem = new javax.swing.JButton();
        btEliminaMem = new javax.swing.JButton();
        btActualizaMem = new javax.swing.JButton();
        btCancelaMem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbTipoMem = new javax.swing.JComboBox<>();
        etTipoMem = new javax.swing.JLabel();
        spPuntosMem = new javax.swing.JSpinner();
        etPuntosMem = new javax.swing.JLabel();
        etMensajeMem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMembresia = new javax.swing.JTable();
        panelPelicula = new javax.swing.JPanel();
        panelInfoEmp3 = new javax.swing.JPanel();
        btAgregaPel = new javax.swing.JButton();
        btEliminaPel = new javax.swing.JButton();
        btActualizaPel = new javax.swing.JButton();
        btCancelaPel = new javax.swing.JButton();
        etMensajePel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ctNombrePel = new javax.swing.JTextField();
        etNombrePel = new javax.swing.JLabel();
        etDirectorPel = new javax.swing.JLabel();
        ctDirectorPel = new javax.swing.JTextField();
        rbAPel = new javax.swing.JRadioButton();
        rbBPel = new javax.swing.JRadioButton();
        rbCPel = new javax.swing.JRadioButton();
        cbGeneroPel = new javax.swing.JComboBox<>();
        etGeneroPel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSinopsisPel = new javax.swing.JTextArea();
        etSinopsisPel = new javax.swing.JLabel();
        etClasificacionPel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPelicula = new javax.swing.JTable();
        panelSucursal = new javax.swing.JPanel();
        panelFuncion = new javax.swing.JPanel();
        panelVentas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinemax");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(985, 565));

        tpPrincipal.setPreferredSize(new java.awt.Dimension(1000, 600));

        tpAdministración.setOpaque(true);

        panelEmpleado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelEmpleadoComponentShown(evt);
            }
        });

        panelInfoEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));

        etNombreEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etNombreEmp.setText("Nombre (s)");

        etAppEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etAppEmp.setText("Apellido paterno");

        etApmEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etApmEmp.setText("Apellido materno");

        etFechaEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etFechaEmp.setText("Fecha de nacimiento");

        etContEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etContEmp.setText("Contraseña");

        ctNombreEmp.setName("ctNombreEmp"); // NOI18N

        ctAppEmp.setName("ctAppEmp"); // NOI18N

        ctApmEmp.setName("ctApmEmp"); // NOI18N

        ctFechaEmp.setName("ctFechaEmp"); // NOI18N

        ctContEmp.setName("ctContEmp"); // NOI18N

        etFechaEmp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etFechaEmp1.setText("AAAA-MM-DD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(etFechaEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(etApmEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ctApmEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(etFechaEmp1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctFechaEmp))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(etContEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctContEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etAppEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etNombreEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ctNombreEmp)
                                    .addComponent(ctAppEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etNombreEmp)
                    .addComponent(ctNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctAppEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAppEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctApmEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etApmEmp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctFechaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etFechaEmp)
                    .addComponent(etFechaEmp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctContEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etContEmp)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de contacto"));

        etColoniaEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etColoniaEmp.setText("Colonia");

        etNumeroEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etNumeroEmp.setText("Numero");

        etCalleEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etCalleEmp.setText("Calle");

        ctColoniaEmp.setName("ctColoniaEmp"); // NOI18N

        ctCalleEmp.setName("ctCalleEmp"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etCalleEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etColoniaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ctCalleEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(ctColoniaEmp)
                    .addComponent(ctNumeroEmp))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etColoniaEmp)
                    .addComponent(ctColoniaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etCalleEmp)
                    .addComponent(ctCalleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNumeroEmp))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btAgregaEmp.setText("Agregar");
        btAgregaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregaEmpActionPerformed(evt);
            }
        });

        btEliminaEmp.setText("Eliminar");
        btEliminaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaEmpActionPerformed(evt);
            }
        });

        btActualizaEmp.setText("Actualizar");
        btActualizaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizaEmpActionPerformed(evt);
            }
        });

        btCancelaEmp.setText("Cancelar");
        btCancelaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaEmpActionPerformed(evt);
            }
        });

        etMensajeEmp.setText("Mensaje");

        javax.swing.GroupLayout panelInfoEmpLayout = new javax.swing.GroupLayout(panelInfoEmp);
        panelInfoEmp.setLayout(panelInfoEmpLayout);
        panelInfoEmpLayout.setHorizontalGroup(
            panelInfoEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInfoEmpLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(panelInfoEmpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(etMensajeEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelaEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btActualizaEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEliminaEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAgregaEmp)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelInfoEmpLayout.setVerticalGroup(
            panelInfoEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmpLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etMensajeEmp)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelInfoEmpLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelInfoEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelaEmp)
                    .addComponent(btActualizaEmp)
                    .addComponent(btEliminaEmp)
                    .addComponent(btAgregaEmp)))
        );

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaEmpleado);

        javax.swing.GroupLayout panelEmpleadoLayout = new javax.swing.GroupLayout(panelEmpleado);
        panelEmpleado.setLayout(panelEmpleadoLayout);
        panelEmpleadoLayout.setHorizontalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panelEmpleadoLayout.setVerticalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpAdministración.addTab("Empleado", panelEmpleado);
        panelEmpleado.getAccessibleContext().setAccessibleName("");

        panelMembresia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelMembresiaComponentShown(evt);
            }
        });

        panelInfoEmp2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));

        etNombreMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etNombreMem.setText("Nombre (s)");

        etAppMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etAppMem.setText("Apellido paterno");

        etApmMem.setText("Apellido materno");

        etFechaMem.setText("Fecha de nacimiento");

        etFechaEmp2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etFechaEmp2.setText("AAAA-MM-DD");

        ctFechaMem.setName("ctFechaEmp"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(etFechaMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etFechaEmp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctFechaMem))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(etNombreMem, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctNombreMem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(etApmMem))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(etAppMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ctAppMem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(ctApmMem, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etNombreMem)
                    .addComponent(ctNombreMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctAppMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAppMem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctApmMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etApmMem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFechaMem)
                    .addComponent(ctFechaMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etFechaEmp2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de contacto"));

        etColoniaMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etColoniaMem.setText("Colonia");

        etNumeroMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etNumeroMem.setText("Numero");

        etCalleMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etCalleMem.setText("Calle");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etColoniaMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etNumeroMem, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(etCalleMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctNumeroMem, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(ctCalleMem)
                    .addComponent(ctColoniaMem))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etColoniaMem)
                    .addComponent(ctColoniaMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etCalleMem)
                    .addComponent(ctCalleMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctNumeroMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNumeroMem))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btAgregaMem.setText("Agregar");
        btAgregaMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregaMemActionPerformed(evt);
            }
        });

        btEliminaMem.setText("Eliminar");
        btEliminaMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaMemActionPerformed(evt);
            }
        });

        btActualizaMem.setText("Actualizar");
        btActualizaMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizaMemActionPerformed(evt);
            }
        });

        btCancelaMem.setText("Cancelar");
        btCancelaMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaMemActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de membresia"));

        cbTipoMem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standar", "Premium", "Vip" }));

        etTipoMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etTipoMem.setText("Tipo");

        etPuntosMem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etPuntosMem.setText("Puntos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etTipoMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etPuntosMem, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoMem, 0, 162, Short.MAX_VALUE)
                    .addComponent(spPuntosMem))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etTipoMem)
                    .addComponent(cbTipoMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spPuntosMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPuntosMem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etMensajeMem.setText("Mensaje");

        javax.swing.GroupLayout panelInfoEmp2Layout = new javax.swing.GroupLayout(panelInfoEmp2);
        panelInfoEmp2.setLayout(panelInfoEmp2Layout);
        panelInfoEmp2Layout.setHorizontalGroup(
            panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                .addGroup(panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(etMensajeMem))
                    .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoEmp2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelaMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btActualizaMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEliminaMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAgregaMem)))
                .addContainerGap())
        );
        panelInfoEmp2Layout.setVerticalGroup(
            panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                .addGroup(panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(etMensajeMem))
                    .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfoEmp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancelaMem)
                            .addComponent(btActualizaMem)
                            .addComponent(btEliminaMem)
                            .addComponent(btAgregaMem))))
                .addGap(18, 18, 18))
            .addGroup(panelInfoEmp2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaMembresia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMembresia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMembresiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMembresia);

        javax.swing.GroupLayout panelMembresiaLayout = new javax.swing.GroupLayout(panelMembresia);
        panelMembresia.setLayout(panelMembresiaLayout);
        panelMembresiaLayout.setHorizontalGroup(
            panelMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembresiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoEmp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelMembresiaLayout.setVerticalGroup(
            panelMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembresiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfoEmp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpAdministración.addTab("Membresía", panelMembresia);

        panelPelicula.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelPeliculaComponentShown(evt);
            }
        });

        panelInfoEmp3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        btAgregaPel.setText("Agregar");
        btAgregaPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregaPelActionPerformed(evt);
            }
        });

        btEliminaPel.setText("Eliminar");
        btEliminaPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaPelActionPerformed(evt);
            }
        });

        btActualizaPel.setText("Actualizar");
        btActualizaPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizaPelActionPerformed(evt);
            }
        });

        btCancelaPel.setText("Cancelar");
        btCancelaPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaPelActionPerformed(evt);
            }
        });

        etMensajePel.setText("Mensaje");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos generales"));

        etNombrePel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etNombrePel.setText("Nombre");

        etDirectorPel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etDirectorPel.setText("Director");

        rbAPel.setText("A (Todos)");

        rbBPel.setText("B (15 años +)");

        rbCPel.setText("C (18 años +)");

        cbGeneroPel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terror", "Comedia", "Accion", "Ciencia Ficcion", "Animacion", "Infantil", "Misterio", "Drama" }));

        etGeneroPel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etGeneroPel.setText("Genero");

        taSinopsisPel.setColumns(20);
        taSinopsisPel.setRows(5);
        jScrollPane1.setViewportView(taSinopsisPel);

        etSinopsisPel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etSinopsisPel.setText("Sinopsis");

        etClasificacionPel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etClasificacionPel.setText("Clasificacion");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etDirectorPel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(etNombrePel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etGeneroPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etClasificacionPel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rbCPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbBPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAPel))
                    .addComponent(ctDirectorPel)
                    .addComponent(ctNombrePel)
                    .addComponent(cbGeneroPel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etSinopsisPel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etNombrePel)
                            .addComponent(ctNombrePel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etSinopsisPel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctDirectorPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etDirectorPel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCPel)
                            .addComponent(rbBPel)
                            .addComponent(rbAPel)
                            .addComponent(etClasificacionPel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etGeneroPel)
                            .addComponent(cbGeneroPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInfoEmp3Layout = new javax.swing.GroupLayout(panelInfoEmp3);
        panelInfoEmp3.setLayout(panelInfoEmp3Layout);
        panelInfoEmp3Layout.setHorizontalGroup(
            panelInfoEmp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmp3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoEmp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInfoEmp3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(etMensajePel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelaPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btActualizaPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEliminaPel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAgregaPel)))
                .addContainerGap())
        );
        panelInfoEmp3Layout.setVerticalGroup(
            panelInfoEmp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmp3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoEmp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelaPel)
                    .addComponent(btActualizaPel)
                    .addComponent(btEliminaPel)
                    .addComponent(btAgregaPel)
                    .addComponent(etMensajePel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tablaPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeliculaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaPelicula);

        javax.swing.GroupLayout panelPeliculaLayout = new javax.swing.GroupLayout(panelPelicula);
        panelPelicula.setLayout(panelPeliculaLayout);
        panelPeliculaLayout.setHorizontalGroup(
            panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoEmp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPeliculaLayout.setVerticalGroup(
            panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfoEmp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpAdministración.addTab("Película", panelPelicula);

        javax.swing.GroupLayout panelSucursalLayout = new javax.swing.GroupLayout(panelSucursal);
        panelSucursal.setLayout(panelSucursalLayout);
        panelSucursalLayout.setHorizontalGroup(
            panelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        panelSucursalLayout.setVerticalGroup(
            panelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tpAdministración.addTab("Sucursal", panelSucursal);

        javax.swing.GroupLayout panelFuncionLayout = new javax.swing.GroupLayout(panelFuncion);
        panelFuncion.setLayout(panelFuncionLayout);
        panelFuncionLayout.setHorizontalGroup(
            panelFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        panelFuncionLayout.setVerticalGroup(
            panelFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tpAdministración.addTab("Función", panelFuncion);

        javax.swing.GroupLayout panelAdministracionLayout = new javax.swing.GroupLayout(panelAdministracion);
        panelAdministracion.setLayout(panelAdministracionLayout);
        panelAdministracionLayout.setHorizontalGroup(
            panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAdministración)
        );
        panelAdministracionLayout.setVerticalGroup(
            panelAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpAdministración, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Administración", panelAdministracion);

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Ventas", panelVentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 576, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    // <editor-fold defaultstate="collapsed" desc="Eventos de la pestaña empleados">
    private void btAgregaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregaEmpActionPerformed
       agregaEmpleado();
    }//GEN-LAST:event_btAgregaEmpActionPerformed

    private void panelEmpleadoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelEmpleadoComponentShown
        actualizaTablaEmpleados();
        etMensajeEmp.setVisible(false);
        habilitaEdicionEmpleado(false);
    }//GEN-LAST:event_panelEmpleadoComponentShown

    private void tablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadoMouseClicked
        if (tablaEmpleado.getSelectedRow() > -1) {
            cargaDatosEmpleado();
            etMensajeEmp.setVisible(false);
        }
    }//GEN-LAST:event_tablaEmpleadoMouseClicked

    private void btActualizaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizaEmpActionPerformed
        actualizaEmpleado();
    }//GEN-LAST:event_btActualizaEmpActionPerformed

    private void btEliminaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaEmpActionPerformed
        eliminaEmpleado();
    }//GEN-LAST:event_btEliminaEmpActionPerformed

    private void btCancelaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaEmpActionPerformed
        habilitaEdicionEmpleado(false);
    }//GEN-LAST:event_btCancelaEmpActionPerformed

    private void btAgregaMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregaMemActionPerformed
        agregaMembresia();
    }//GEN-LAST:event_btAgregaMemActionPerformed

    private void tablaMembresiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMembresiaMouseClicked
        if (tablaMembresia.getSelectedRow() > -1) {
            cargaDatosMembresia();
            etMensajeMem.setVisible(false);
        }
    }//GEN-LAST:event_tablaMembresiaMouseClicked

    private void btActualizaMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizaMemActionPerformed
        actualizaMembresia();
    }//GEN-LAST:event_btActualizaMemActionPerformed

    private void btEliminaMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaMemActionPerformed
        eliminaMembresia();
    }//GEN-LAST:event_btEliminaMemActionPerformed

    private void btCancelaMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaMemActionPerformed
        habilitaEdicionMembresia(false);
    }//GEN-LAST:event_btCancelaMemActionPerformed

    private void panelMembresiaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelMembresiaComponentShown
        actualizaTablaMembresia();
        etMensajeMem.setVisible(false);
        habilitaEdicionMembresia(false);
    }//GEN-LAST:event_panelMembresiaComponentShown

    private void btAgregaPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregaPelActionPerformed
        agregaPelicula();
    }//GEN-LAST:event_btAgregaPelActionPerformed

    private void btEliminaPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaPelActionPerformed
        eliminaPelicula();
    }//GEN-LAST:event_btEliminaPelActionPerformed

    private void btActualizaPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizaPelActionPerformed
        actualizaPelicula();
    }//GEN-LAST:event_btActualizaPelActionPerformed

    private void btCancelaPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaPelActionPerformed
        habilitaEdicionPelicula(false);
    }//GEN-LAST:event_btCancelaPelActionPerformed

    private void tablaPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeliculaMouseClicked
        if (tablaPelicula.getSelectedRow() > -1) {
            cargaDatosPelicula();
            etMensajePel.setVisible(false);
        }
    }//GEN-LAST:event_tablaPeliculaMouseClicked

    private void panelPeliculaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelPeliculaComponentShown
        actualizaTablaPelicula();
        etMensajePel.setVisible(false);
        habilitaEdicionPelicula(false);
    }//GEN-LAST:event_panelPeliculaComponentShown
   
    // </editor-fold>     
    
    // <editor-fold defaultstate="collapsed" desc="Metodos de la pestaña empleados">   
    private void habilitaEdicionEmpleado(boolean visible){
        if(visible) {
            btActualizaEmp.setVisible(true);
            btEliminaEmp.setVisible(true);
            btCancelaEmp.setVisible(true);
            btAgregaEmp.setVisible(false);
        }
        else {
            limpiaFormularioEmpleado();
            limpiaCamposEmpleado();
            btActualizaEmp.setVisible(false);
            btEliminaEmp.setVisible(false);
            btCancelaEmp.setVisible(false);
            btAgregaEmp.setVisible(true);
        }
        //etMensajeEmp.setVisible(false);
    }
    
    private void agregaEmpleado() {
        EmpleadoConexion conEmp;
        Empleado empleado;
        limpiaFormularioEmpleado();
        
        if(validaDatosEmpleado())
        {
            conEmp = new EmpleadoConexion();
            empleado = new Empleado();
            empleado.setNombres(ctNombreEmp.getText());
            empleado.setApp(ctAppEmp.getText());
            empleado.setApm(ctApmEmp.getText());        
            empleado.setFecha_nac(Date.valueOf(ctFechaEmp.getText()));
            empleado.setContraseña(ctContEmp.getText());
            empleado.setColonia(ctColoniaEmp.getText());
            empleado.setCalle(ctCalleEmp.getText());        
            empleado.setNumero(Integer.parseInt(ctNumeroEmp.getText()));  
            empleado.setContraseña(ctContEmp.getText());

            if(conEmp.inserta(empleado)) {
                limpiaCamposEmpleado();
                cambiaTextoMensajeEmp("Se agregó correctamente!",Color.BLUE);
                etMensajeEmp.setVisible(true);
                actualizaTablaEmpleados();
            }
            else {
                cambiaTextoMensajeEmp("Empleado no insertado",Color.RED); 
                etMensajeEmp.setVisible(true);
            }
        }
    }
    
    private void actualizaEmpleado() {
        EmpleadoConexion conEmp;
        Empleado empleado;
        limpiaFormularioEmpleado();
        
        if(validaDatosEmpleado())
        {
            conEmp = new EmpleadoConexion();
            empleado = new Empleado();
            empleado.setClave_emp(Long.parseLong(tablaEmpleado.getValueAt(tablaEmpleado.getSelectedRow(), 0).toString()));
            empleado.setNombres(ctNombreEmp.getText());
            empleado.setApp(ctAppEmp.getText());
            empleado.setApm(ctApmEmp.getText());        
            empleado.setFecha_nac(Date.valueOf(ctFechaEmp.getText()));
            empleado.setContraseña(ctContEmp.getText());
            empleado.setColonia(ctColoniaEmp.getText());
            empleado.setCalle(ctCalleEmp.getText());        
            empleado.setNumero(Integer.parseInt(ctNumeroEmp.getText()));  
            empleado.setContraseña(ctContEmp.getText());
            if(conEmp.actualiza(empleado)) {
                cambiaTextoMensajeEmp("Se actualizó correctamente!",Color.BLUE);
                etMensajeEmp.setVisible(true);
                actualizaTablaEmpleados();
            }
            else {
                cambiaTextoMensajeEmp("Empleado no actualizado",Color.RED); 
                etMensajeEmp.setVisible(true);
            }
            habilitaEdicionEmpleado(false);
        }
    }
    
    private void eliminaEmpleado() {
        EmpleadoConexion conEmp;
        Empleado empleado;
        limpiaFormularioEmpleado();
        
        conEmp = new EmpleadoConexion();
        empleado = new Empleado();
        empleado.setClave_emp(Long.parseLong(tablaEmpleado.getValueAt(tablaEmpleado.getSelectedRow(), 0).toString()));
        int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este registro?", "Atención", JOptionPane.YES_NO_OPTION);
        if(opcion == 0){
            if(conEmp.elimina(empleado)) {
                cambiaTextoMensajeEmp("Se eliminó correctamente!",Color.BLUE);
                etMensajeEmp.setVisible(true);
                actualizaTablaEmpleados();
            }
            else {
                cambiaTextoMensajeEmp("Empleado no eliminado",Color.RED); 
                etMensajeEmp.setVisible(true);
            }
            habilitaEdicionEmpleado(false);
        }        
    }
    
    private boolean validaDatosEmpleado(){
        boolean valido = true;
        int error = 0;
        
        if (ctNombreEmp.getText().trim().equals("")) { etNombreEmp.setText("Nombre (s) *") ; error++; }
        if (ctAppEmp.getText().trim().equals("")) { etAppEmp.setText("Apellido paterno *"); error++; }
        if (ctApmEmp.getText().trim().equals("")) { etApmEmp.setText("Apellido materno *"); error++; }
        if (ctFechaEmp.getText().trim().equals("")) { etFechaEmp.setText("Fecha de nacimiento *"); error++; }
        if (ctColoniaEmp.getText().trim().equals("")) { etColoniaEmp.setText("Colonia *"); error++; }
        if (ctCalleEmp.getText().trim().equals("")) { etCalleEmp.setText("Calle *"); error++; }
        if (ctNumeroEmp.getText().trim().equals("")) { etNumeroEmp.setText("Numero *"); error++; }
        if (ctContEmp.getText().trim().equals("")) { etContEmp.setText("Contraseña *"); error++; }

        if (error > 0) { cambiaTextoMensajeEmp("* Campos requeridos!",Color.RED) ; etMensajeEmp.setVisible(true); valido = false; }   
        
        return valido;
    }
    
    private void cambiaTextoMensajeEmp(String mensaje, Color color){
        etMensajeEmp.setText(mensaje);
        etMensajeEmp.setForeground(color);
    }
    
    private void limpiaCamposEmpleado() {
        ctNombreEmp.setText("");
        ctAppEmp.setText("");
        ctApmEmp.setText("");
        ctFechaEmp.setText("");
        ctColoniaEmp.setText("");
        ctCalleEmp.setText("");
        ctNumeroEmp.setText("");
        ctContEmp.setText("");
    }
    
    private void limpiaFormularioEmpleado() {
        etNombreEmp.setText("Nombre (s)");
        etAppEmp.setText("Apellido paterno");
        etApmEmp.setText("Apellido materno");
        etFechaEmp.setText("Fecha de nacimiento");
        etColoniaEmp.setText("Colonia");
        etCalleEmp.setText("Calle");
        etNumeroEmp.setText("Numero");
        etContEmp.setText("Contraseña");
    }     
    
    private void actualizaTablaEmpleados() {
        EmpleadoConexion con;

        con = new EmpleadoConexion();
        try {
            tablaEmpleado.setModel(con.getDatosTabla());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),  "Error al cargar los datos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargaDatosEmpleado() {
        int renglon = tablaEmpleado.getSelectedRow();
        
        ctNombreEmp.setText(tablaEmpleado.getValueAt(renglon, 1).toString());
        ctAppEmp.setText(tablaEmpleado.getValueAt(renglon, 2).toString());
        ctApmEmp.setText(tablaEmpleado.getValueAt(renglon, 3).toString());        
        ctFechaEmp.setText(tablaEmpleado.getValueAt(renglon, 4).toString());
        ctColoniaEmp.setText(tablaEmpleado.getValueAt(renglon, 5).toString());
        ctCalleEmp.setText(tablaEmpleado.getValueAt(renglon, 6).toString());        
        ctNumeroEmp.setText(tablaEmpleado.getValueAt(renglon, 7).toString());  
        ctContEmp.setText(tablaEmpleado.getValueAt(renglon, 8).toString());
        habilitaEdicionEmpleado(true);
    }
    // </editor-fold>  
    
    // <editor-fold defaultstate="collapsed" desc="Metodos de la pestaña membresia">
    
    private void habilitaEdicionMembresia(boolean visible){
        if(visible) {
            btActualizaMem.setVisible(true);
            btEliminaMem.setVisible(true);
            btCancelaMem.setVisible(true);
            btAgregaMem.setVisible(false);
        }
        else {
            limpiaFormularioMembresia();
            limpiaCamposMembresia();
            btActualizaMem.setVisible(false);
            btEliminaMem.setVisible(false);
            btCancelaMem.setVisible(false);
            btAgregaMem.setVisible(true);
        }
        //etMensajeMem.setVisible(false);
    }
        
    private void agregaMembresia(){
        
        MembresiaConexion conMem;
        Membresia membresia;
        limpiaFormularioMembresia();
        
        if(validaDatosMembresia())
        {
            conMem = new MembresiaConexion();
            membresia = new Membresia();
            membresia.setNombre(ctNombreMem.getText());
            membresia.setApp(ctAppMem.getText());
            membresia.setApm(ctApmMem.getText());        
            membresia.setFecha_nac(Date.valueOf(ctFechaMem.getText()));
            membresia.setColonia(ctColoniaMem.getText());
            membresia.setCalle(ctCalleMem.getText());        
            membresia.setNumero(Integer.parseInt(ctNumeroMem.getText()));
            membresia.setTipo(cbTipoMem.getSelectedItem().toString());
            membresia.setPuntos(Integer.parseInt(spPuntosMem.getValue().toString()));

            if(conMem.inserta(membresia)) {
                limpiaCamposMembresia();
                cambiaTextoMensajeMem("Se agregó correctamente!",Color.BLUE);
                etMensajeMem.setVisible(true);
                actualizaTablaMembresia();
            }
            else {
                cambiaTextoMensajeMem("Empleado no insertado",Color.RED); 
                etMensajeMem.setVisible(true);
            }
        }   
    }
    
    private void actualizaMembresia() {
        MembresiaConexion conMem;
        Membresia membresia;
        limpiaFormularioMembresia();
        
        if(validaDatosMembresia())
        {
            conMem = new MembresiaConexion();
            membresia = new Membresia();
            membresia.setClave_mem(Long.parseLong(tablaMembresia.getValueAt(tablaMembresia.getSelectedRow(), 0).toString()));
            membresia.setNombre(ctNombreMem.getText());
            membresia.setApp(ctAppMem.getText());
            membresia.setApm(ctApmMem.getText());        
            membresia.setFecha_nac(Date.valueOf(ctFechaMem.getText()));
            membresia.setColonia(ctColoniaMem.getText());
            membresia.setCalle(ctCalleMem.getText());        
            membresia.setNumero(Integer.parseInt(ctNumeroMem.getText()));
            membresia.setTipo(cbTipoMem.getSelectedItem().toString());
            membresia.setPuntos(Integer.parseInt(spPuntosMem.getValue().toString()));
            
            if(conMem.actualiza(membresia)) {
                cambiaTextoMensajeMem("Se actualizó correctamente!",Color.BLUE);
                etMensajeMem.setVisible(true);
                actualizaTablaMembresia();
            }
            else {
                cambiaTextoMensajeMem("Membresia no actualizado",Color.RED); 
                etMensajeMem.setVisible(true);
            }
            habilitaEdicionMembresia(false);
        }
    }
    
    private void eliminaMembresia() {
        MembresiaConexion conMem;
        Membresia membresia;
        limpiaFormularioMembresia();
        
        conMem = new MembresiaConexion();
        membresia = new Membresia();
        membresia.setClave_mem(Long.parseLong(tablaMembresia.getValueAt(tablaMembresia.getSelectedRow(), 0).toString()));
        int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este registro?", "Atención", JOptionPane.YES_NO_OPTION);
        if(opcion == 0){
            if(conMem.elimina(membresia)) {
                cambiaTextoMensajeMem("Se eliminó correctamente!",Color.BLUE);
                etMensajeMem.setVisible(true);
                actualizaTablaMembresia();
            }
            else {
                cambiaTextoMensajeMem("Membresia no eliminada",Color.RED); 
                etMensajeMem.setVisible(true);
            }
            habilitaEdicionMembresia(false);
        }
        
    }
    
    private void limpiaFormularioMembresia() {
        etNombreMem.setText("Nombre (s)");
        etAppMem.setText("Apellido paterno");
        etApmMem.setText("Apellido materno");
        etFechaMem.setText("Fecha de nacimiento");
        etColoniaMem.setText("Colonia");
        etCalleMem.setText("Calle");
        etNumeroMem.setText("Numero");
        etTipoMem.setText("Tipo");
        etPuntosMem.setText("Puntos");
    }
    
    private boolean validaDatosMembresia(){
        boolean valido = true;
        int error = 0;
        
        if (ctNombreMem.getText().trim().equals("")) { etNombreMem.setText("Nombre (s) *") ; error++; }
        if (ctAppMem.getText().trim().equals("")) { etAppMem.setText("Apellido paterno *"); error++; }
        if (ctApmMem.getText().trim().equals("")) { etApmMem.setText("Apellido materno *"); error++; }
        if (ctFechaMem.getText().trim().equals("")) { etFechaMem.setText("Fecha de nacimiento *"); error++; }
        if (ctColoniaMem.getText().trim().equals("")) { etColoniaMem.setText("Colonia *"); error++; }
        if (ctCalleMem.getText().trim().equals("")) { etCalleMem.setText("Calle *"); error++; }
        if (ctNumeroMem.getText().trim().equals("")) { etNumeroMem.setText("Numero *"); error++; }
        if (cbTipoMem.getSelectedIndex() == -1) { etTipoMem.setText("Tipo *"); error++; }
        
        if (error > 0) { cambiaTextoMensajeMem("* Campos requeridos!",Color.RED) ; etMensajeMem.setVisible(true); valido = false; }   
        
        return valido;
    }
    
    private void cambiaTextoMensajeMem(String mensaje, Color color){
        etMensajeMem.setText(mensaje);
        etMensajeMem.setForeground(color);
    }
    
    private void limpiaCamposMembresia() {
        ctNombreMem.setText("");
        ctAppMem.setText("");
        ctApmMem.setText("");
        ctFechaMem.setText("");
        ctColoniaMem.setText("");        
        ctCalleMem.setText("");
        ctNumeroMem.setText("");
        cbTipoMem.setSelectedIndex(-1);
        spPuntosMem.setValue(0);
    }
    
    private void actualizaTablaMembresia() {
        MembresiaConexion con;

        con = new MembresiaConexion();
        try {
            tablaMembresia.setModel(con.getDatosTabla());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),  "Error al cargar los datos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargaDatosMembresia() {
        int renglon = tablaMembresia.getSelectedRow();
        
        ctNombreMem.setText(tablaMembresia.getValueAt(renglon, 1).toString());
        ctAppMem.setText(tablaMembresia.getValueAt(renglon, 2).toString());
        ctApmMem.setText(tablaMembresia.getValueAt(renglon, 3).toString());        
        ctFechaMem.setText(tablaMembresia.getValueAt(renglon, 4).toString());
        ctColoniaMem.setText(tablaMembresia.getValueAt(renglon, 5).toString());
        ctCalleMem.setText(tablaMembresia.getValueAt(renglon, 6).toString());        
        ctNumeroMem.setText(tablaMembresia.getValueAt(renglon, 7).toString());
        cbTipoMem.setSelectedItem(tablaMembresia.getValueAt(renglon, 8).toString());
        spPuntosMem.setValue(tablaMembresia.getValueAt(renglon, 9));
        habilitaEdicionMembresia(true);
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Metodos de la pestaña pelicula">
    
    private void habilitaEdicionPelicula(boolean visible){
        if(visible) {
            btActualizaPel.setVisible(true);
            btEliminaPel.setVisible(true);
            btCancelaPel.setVisible(true);
            btAgregaPel.setVisible(false);
        }
        else {
            limpiaFormularioPelicula();
            limpiaCamposPelicula();
            btActualizaPel.setVisible(false);
            btEliminaPel.setVisible(false);
            btCancelaPel.setVisible(false);
            btAgregaPel.setVisible(true);
        }
        //etMensajeMem.setVisible(false);
    }
    
    private void agregaPelicula(){
        
        PeliculaConexion conPel;
        Pelicula pelicula;
        limpiaFormularioPelicula();
        
        if(validaDatosPelicula())
        {
            conPel = new PeliculaConexion();
            pelicula = new Pelicula();
            pelicula.setNombre(ctNombrePel.getText());
            pelicula.setDirector(ctDirectorPel.getText());
            pelicula.setClasificacion(clasificacionPelicula());        
            pelicula.setGenero(cbGeneroPel.getSelectedItem().toString());
            pelicula.setSinopsis(taSinopsisPel.getText());

            if(conPel.inserta(pelicula)) {
                limpiaCamposPelicula();
                cambiaTextoMensajePel("Se agregó correctamente!",Color.BLUE);
                etMensajePel.setVisible(true);
                actualizaTablaPelicula();
            }
            else {
                cambiaTextoMensajePel("Pelicula no insertado",Color.RED); 
                etMensajePel.setVisible(true);
            }
        }   
    }
    
    private void actualizaPelicula() {
        PeliculaConexion conPel;
        Pelicula pelicula;
        limpiaFormularioPelicula();
        
        if(validaDatosPelicula())
        {
            conPel = new PeliculaConexion();
            pelicula = new Pelicula();
            pelicula.setClave_pel(Long.parseLong(tablaPelicula.getValueAt(tablaPelicula.getSelectedRow(), 0).toString()));
            pelicula.setNombre(ctNombrePel.getText());
            pelicula.setDirector(ctDirectorPel.getText());
            pelicula.setClasificacion(clasificacionPelicula());        
            pelicula.setGenero(cbGeneroPel.getSelectedItem().toString());
            pelicula.setSinopsis(taSinopsisPel.getText());
            
            if(conPel.actualiza(pelicula)) {
                cambiaTextoMensajePel("Se actualizó correctamente!",Color.BLUE);
                etMensajePel.setVisible(true);
                actualizaTablaPelicula();
            }
            else {
                cambiaTextoMensajePel("Pelicula no actualizado",Color.RED); 
                etMensajePel.setVisible(true);
            }
            habilitaEdicionPelicula(false);
        }
    }
    
    private void eliminaPelicula() {
        PeliculaConexion conPel;
        Pelicula pelicula;
        limpiaFormularioPelicula();
        
        conPel = new PeliculaConexion();
        pelicula = new Pelicula();
        pelicula.setClave_pel(Long.parseLong(tablaPelicula.getValueAt(tablaPelicula.getSelectedRow(), 0).toString()));
        int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este registro?", "Atención", JOptionPane.YES_NO_OPTION);
        if(opcion == 0){
            if(conPel.elimina(pelicula)) {
                cambiaTextoMensajePel("Se eliminó correctamente!",Color.BLUE);
                etMensajePel.setVisible(true);
                actualizaTablaPelicula();
            }
            else {
                cambiaTextoMensajePel("Membresia no eliminada",Color.RED); 
                etMensajePel.setVisible(true);
            }
            habilitaEdicionPelicula(false);
        }
        
    }
    
    private void limpiaFormularioPelicula() {
        etNombrePel.setText("Nombre");
        etDirectorPel.setText("Director");
        etClasificacionPel.setText("Casificación");
        etGeneroPel.setText("Genero");
        etSinopsisPel.setText("Sinopsis");
    }

    private boolean validaDatosPelicula(){
        boolean valido = true;
        int error = 0;
        
        if (ctNombrePel.getText().trim().equals("")) { etNombrePel.setText("Nombre *") ; error++; }
        if (ctDirectorPel.getText().trim().equals("")) { etDirectorPel.setText("Director *"); error++; }
        if (clasificacionPelicula().equals("")) { etClasificacionPel.setText("Clasificacion *"); error++; }
        if (cbGeneroPel.getSelectedIndex() == -1) { etGeneroPel.setText("Genero *"); error++; }
        if (taSinopsisPel.getText().trim().equals("")) { etSinopsisPel.setText("Sinopsis *"); error++; }
        
        
        if (error > 0) { cambiaTextoMensajePel("* Campos requeridos!",Color.RED) ; etMensajePel.setVisible(true); valido = false; }   
        
        return valido;
    }
    
    private String clasificacionPelicula() {
            String clas = "0";
            
            if (rbAPel.isSelected())
                clas = "A";
            else
                if (rbBPel.isSelected())
                    clas = "B";
                else
                    if (rbCPel.isSelected())
                        clas = "C";

            return clas;
    }
    
    private void clasificacionPelicula(String clas){
        
        switch (clas) { 
            case "A":
                rbAPel.setSelected(true);
                break;
            case "B":
                rbBPel.setSelected(true);
                break;
            case "C":
                rbCPel.setSelected(true);
                break;
            default:
                rbAPel.setSelected(false);
                rbBPel.setSelected(false);
                rbCPel.setSelected(false);
                break;

        }

    }
    
    private void cambiaTextoMensajePel(String mensaje, Color color){
        etMensajePel.setText(mensaje);
        etMensajePel.setForeground(color);
    }
    
    private void limpiaCamposPelicula() {
        ctNombrePel.setText("");
        ctDirectorPel.setText("");
        clasificacionPelicula("0");
        cbGeneroPel.setSelectedIndex(-1);
        taSinopsisPel.setText("");
    }
    
    private void actualizaTablaPelicula() {
        PeliculaConexion con;

        con = new PeliculaConexion();
        try {
            tablaPelicula.setModel(con.getDatosTabla());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),  "Error al cargar los datos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargaDatosPelicula() {
        int renglon = tablaPelicula.getSelectedRow();
        
        ctNombrePel.setText(tablaPelicula.getValueAt(renglon, 1).toString());
        ctDirectorPel.setText(tablaPelicula.getValueAt(renglon, 2).toString());
        taSinopsisPel.setText(tablaPelicula.getValueAt(renglon, 3).toString());
        clasificacionPelicula(tablaPelicula.getValueAt(renglon, 4).toString());
        cbGeneroPel.setSelectedItem(tablaPelicula.getValueAt(renglon, 5).toString());
        habilitaEdicionPelicula(true);
    }
   
    // </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizaEmp;
    private javax.swing.JButton btActualizaMem;
    private javax.swing.JButton btActualizaPel;
    private javax.swing.JButton btAgregaEmp;
    private javax.swing.JButton btAgregaMem;
    private javax.swing.JButton btAgregaPel;
    private javax.swing.JButton btCancelaEmp;
    private javax.swing.JButton btCancelaMem;
    private javax.swing.JButton btCancelaPel;
    private javax.swing.JButton btEliminaEmp;
    private javax.swing.JButton btEliminaMem;
    private javax.swing.JButton btEliminaPel;
    private javax.swing.JComboBox<String> cbGeneroPel;
    private javax.swing.JComboBox<String> cbTipoMem;
    private javax.swing.JTextField ctApmEmp;
    private javax.swing.JTextField ctApmMem;
    private javax.swing.JTextField ctAppEmp;
    private javax.swing.JTextField ctAppMem;
    private javax.swing.JTextField ctCalleEmp;
    private javax.swing.JTextField ctCalleMem;
    private javax.swing.JTextField ctColoniaEmp;
    private javax.swing.JTextField ctColoniaMem;
    private javax.swing.JTextField ctContEmp;
    private javax.swing.JTextField ctDirectorPel;
    private javax.swing.JTextField ctFechaEmp;
    private javax.swing.JTextField ctFechaMem;
    private javax.swing.JTextField ctNombreEmp;
    private javax.swing.JTextField ctNombreMem;
    private javax.swing.JTextField ctNombrePel;
    private javax.swing.JTextField ctNumeroEmp;
    private javax.swing.JTextField ctNumeroMem;
    private javax.swing.JLabel etApmEmp;
    private javax.swing.JLabel etApmMem;
    private javax.swing.JLabel etAppEmp;
    private javax.swing.JLabel etAppMem;
    private javax.swing.JLabel etCalleEmp;
    private javax.swing.JLabel etCalleMem;
    private javax.swing.JLabel etClasificacionPel;
    private javax.swing.JLabel etColoniaEmp;
    private javax.swing.JLabel etColoniaMem;
    private javax.swing.JLabel etContEmp;
    private javax.swing.JLabel etDirectorPel;
    private javax.swing.JLabel etFechaEmp;
    private javax.swing.JLabel etFechaEmp1;
    private javax.swing.JLabel etFechaEmp2;
    private javax.swing.JLabel etFechaMem;
    private javax.swing.JLabel etGeneroPel;
    private javax.swing.JLabel etMensajeEmp;
    private javax.swing.JLabel etMensajeMem;
    private javax.swing.JLabel etMensajePel;
    private javax.swing.JLabel etNombreEmp;
    private javax.swing.JLabel etNombreMem;
    private javax.swing.JLabel etNombrePel;
    private javax.swing.JLabel etNumeroEmp;
    private javax.swing.JLabel etNumeroMem;
    private javax.swing.JLabel etPuntosMem;
    private javax.swing.JLabel etSinopsisPel;
    private javax.swing.JLabel etTipoMem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelAdministracion;
    private javax.swing.JPanel panelEmpleado;
    private javax.swing.JPanel panelFuncion;
    private javax.swing.JPanel panelInfoEmp;
    private javax.swing.JPanel panelInfoEmp2;
    private javax.swing.JPanel panelInfoEmp3;
    private javax.swing.JPanel panelMembresia;
    private javax.swing.JPanel panelPelicula;
    private javax.swing.JPanel panelSucursal;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JRadioButton rbAPel;
    private javax.swing.JRadioButton rbBPel;
    private javax.swing.JRadioButton rbCPel;
    private javax.swing.JSpinner spPuntosMem;
    private javax.swing.JTextArea taSinopsisPel;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTable tablaMembresia;
    private javax.swing.JTable tablaPelicula;
    private javax.swing.JTabbedPane tpAdministración;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables

}
